//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoAdopta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        public int IdAnimal { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> Fecha_nac { get; set; }
        public string Descripcion { get; set; }
        public string Imagen { get; set; }
        public Nullable<int> Peso { get; set; }
    }
}
