//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoAdopta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int IdPedido { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdAnimal { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<System.DateTime> Fecha_Adopcion { get; set; }
    }
}
